Improved error handling in pot2json

diff --git a/.dev/bin/pot2json b/.dev/bin/pot2json
--- a/.dev/bin/pot2json
+++ b/.dev/bin/pot2json
@@ -2,11 +2,22 @@
 <?php
 
 if ( ! isset( $argv[1], $argv[2] ) ) {
-	echo "Error: Missing required arguments\n";
+	echo "Error: Missing required parameters.\n";
 	exit;
 }
 
-$input  = preg_grep( '/^msgid "(.+?)"$/', explode( PHP_EOL, file_get_contents( $argv[1] ) ) );
+$input = preg_grep( '/^msgid "(.+?)"$/', explode( PHP_EOL, file_get_contents( $argv[1] ) ) );
+
+if ( ! $input ) {
+	echo "Error: No input data.\n";
+	exit;
+}
+
+if ( ! is_writable( dirname( $argv[2] ) ) || ( file_exists( $argv[2] ) && ! is_writable( $argv[2] ) ) ) {
+	echo "Error: Target not writable.\n";
+	exit;
+}
+
 $output = [];
 
 foreach ( $input as $line ) {
